### ISSUE TITLE
Comparison with similar libraries (canada, bodyguard, etc).

### ISSUE THREAD

**Issue by tcrossland** [subvisual/dictator#1]
Hi Fernando, thanks for publishing this project. For potential adopters, it might be useful to include in the documentation a comparison with similar libraries such as https://github.com/jarednorman/canada or https://github.com/schrockwell/bodyguard. Just a suggestion.

**Comment by frm** [comment]
Hey!

That’s a really good suggestion! I’m not a big fan of doing it in the README as I’d rather keep it as a small walkthrough across the project. Especially since these comparisons could be considered opinionated, a better option would be to write a blog post on it. I’ll add it to my pipeline and get it out there as soon as I can :smile:

I think it’s a fair idea to give a nudge to similar options and libraries. I’ll add that to the README :+1: Thanks for the suggestions!
